name: Glonet-Inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - xesmf=0.8.5           # Pour le regridding
  - xarray=2024.3.0             # Pour manipuler les .nc
  - netcdf4=1.6.5             # Dépendance pour xarray
  - h5netcdf            # Dépendance pour xarray
  - s3fs                # Pour lire les .nc depuis S3
  - copernicusmarine=1.3.4    # Pour télécharger les données
  - scipy
  - numpy=1.24.4
  - rioxarray
  - matplotlib
  - pillow
  - pip:
    - torch==2.2.2            # Pour le deep learning
    - torchvision==0.17.2      # Pour les transformations (normalizer)
    - boto3             # Pour uploader les fichiers sur S3 (AWS SDK)
    - requests          # Pour télécharger le modèle